print("Mad libs where libs get Mad")
print("	Start Below:")
print("\n\n")
time=input("Number: ")
items=input("Noun (plural): ")
name=input("Name: ").title()
scream=input("Any sentence: ").upper()
action=input("Verb: ")
print("\n	It was "+time+" o'clock when I heard a knock at the door.")
print("	I open the door and there was a box full of chocolate milk with a note saying from \"From Mr. "+name+'".')
print('	Just as I closed the door I heard a scream "'+scream+'".')
print("	I froze in place and all I could do was run.")